server:
    port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.136.130:13307/es?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    min-idle: 3
    max-wait: 60000
    max-active: 20
    min-evictable-idle-time-millis: 300000

##### spring actuator #####
management:
  security:
    enabled: false
endpoints:
  beans:
    path: /nihao/hello

