server:
    port: 80
#    address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://192.168.136.130:13306/pay?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    min-idle: 3
    max-wait: 60000
    max-active: 20
    min-evictable-idle-time-millis: 300000