server:
    port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.136.130:13306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    min-idle: 3
    max-wait: 60000
    max-active: 20
    min-evictable-idle-time-millis: 300000

